name: just_throttle_it
description: A simple throttle library for limiting consecutive execution of functions
version: 1.0.0
homepage: https://github.com/truthmast/just_throttle_it
author: Matt Hurst <matt@workpail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.6.5